// GENERATED FILE — DO NOT EDIT.
//
// Produced by `pnpm gen` from each component's *.meta.ts.
// Edit the metadata, then re-run. CI fails if this file is stale.
//
// See content/decisions/0004-generated-component-metadata.md

/**
 * Token values for JavaScript that has to compute with one rather than hand
 * it to the browser — chart geometry, canvas rendering, and anything that
 * needs to know what a colour actually is.
 *
 * Prefer `cssVar` in anything that renders. A literal read from `themeValues`
 * is a snapshot of one theme and will not follow a theme or brand change.
 */

/** Every semantic token name. */
export const TOKEN_NAMES = [
  "accent",
  "accent-border",
  "accent-hover",
  "accent-subtle",
  "bg",
  "bg-muted",
  "bg-subtle",
  "border",
  "border-strong",
  "duration",
  "duration-alert",
  "duration-fast",
  "duration-identity-escalate",
  "duration-identity-reveal",
  "duration-identity-swap",
  "duration-skeleton-loop",
  "duration-slow",
  "ease",
  "flag.deceased",
  "flag.provisional",
  "flag.restricted",
  "flag.restricted-bg",
  "focus-ring",
  "focus-ring-offset",
  "font-mono",
  "font-numeric",
  "font-sans",
  "radius",
  "radius-full",
  "radius-lg",
  "radius-sm",
  "radius-xl",
  "shadow",
  "shadow-lg",
  "shadow-md",
  "shadow-sm",
  "status.critical",
  "status.critical-bg",
  "status.critical-border",
  "status.high",
  "status.high-bg",
  "status.high-border",
  "status.low",
  "status.low-bg",
  "status.low-border",
  "status.normal",
  "status.normal-bg",
  "status.normal-border",
  "status.unknown",
  "status.unknown-bg",
  "status.unknown-border",
  "surface",
  "surface-overlay",
  "surface-raised",
  "swatch.1",
  "swatch.1-bg",
  "swatch.1-border",
  "swatch.2",
  "swatch.2-bg",
  "swatch.2-border",
  "swatch.3",
  "swatch.3-bg",
  "swatch.3-border",
  "swatch.4",
  "swatch.4-bg",
  "swatch.4-border",
  "swatch.5",
  "swatch.5-bg",
  "swatch.5-border",
  "swatch.6",
  "swatch.6-bg",
  "swatch.6-border",
  "text",
  "text-2xl",
  "text-2xs",
  "text-base",
  "text-lg",
  "text-md",
  "text-muted",
  "text-on-accent",
  "text-sm",
  "text-subtle",
  "text-xl",
  "text-xs",
] as const;

export type TokenName = (typeof TOKEN_NAMES)[number];

/** `cssVar("status.critical")` → `"var(--ox-status-critical)"`. */
export function cssVar(name: TokenName): string {
  return `var(--ox-${name.split(".").join("-")})`;
}

export const THEMES = [
  "light",
  "dark",
  "high-contrast",
] as const;

export type Theme = (typeof THEMES)[number];

/** Resolved literals, per theme. */
export const themeValues: Record<Theme, Record<TokenName, string>> = {
  "light": {
    "accent": "#067662",
    "accent-border": "#a4f3df",
    "accent-hover": "#0a5d4f",
    "accent-subtle": "#ecfdf8",
    "bg": "#ffffff",
    "bg-muted": "#f1f5f9",
    "bg-subtle": "#f8fafc",
    "border": "#e2e8f0",
    "border-strong": "#64748b",
    "duration": "180ms",
    "duration-alert": "0ms",
    "duration-fast": "120ms",
    "duration-identity-escalate": "260ms",
    "duration-identity-reveal": "220ms",
    "duration-identity-swap": "180ms",
    "duration-skeleton-loop": "1400ms",
    "duration-slow": "280ms",
    "ease": "cubic-bezier(0.22, 1, 0.36, 1)",
    "flag.deceased": "#334155",
    "flag.provisional": "#b45309",
    "flag.restricted": "#7c3aed",
    "flag.restricted-bg": "#f5f3ff",
    "focus-ring": "#059478",
    "focus-ring-offset": "#ffffff",
    "font-mono": "ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, monospace",
    "font-numeric": "ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, monospace",
    "font-sans": "ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif",
    "radius": "0.5rem",
    "radius-full": "9999px",
    "radius-lg": "0.75rem",
    "radius-sm": "0.25rem",
    "radius-xl": "1rem",
    "shadow": "0 1px 3px 0 rgb(2 6 23 / 0.08), 0 1px 2px -1px rgb(2 6 23 / 0.06)",
    "shadow-lg": "0 12px 32px -8px rgb(2 6 23 / 0.12)",
    "shadow-md": "0 4px 12px -2px rgb(2 6 23 / 0.08), 0 2px 6px -2px rgb(2 6 23 / 0.05)",
    "shadow-sm": "0 1px 2px 0 rgb(2 6 23 / 0.05)",
    "status.critical": "#b91c1c",
    "status.critical-bg": "#fef2f2",
    "status.critical-border": "#fecaca",
    "status.high": "#b45309",
    "status.high-bg": "#fffbeb",
    "status.high-border": "#fde68a",
    "status.low": "#2563eb",
    "status.low-bg": "#eff6ff",
    "status.low-border": "#bfdbfe",
    "status.normal": "#047857",
    "status.normal-bg": "#ecfdf5",
    "status.normal-border": "#a7f3d0",
    "status.unknown": "#64748b",
    "status.unknown-bg": "#f8fafc",
    "status.unknown-border": "#e2e8f0",
    "surface": "#ffffff",
    "surface-overlay": "#ffffff",
    "surface-raised": "#ffffff",
    "swatch.1": "#115e59",
    "swatch.1-bg": "#f0fdfa",
    "swatch.1-border": "#99f6e4",
    "swatch.2": "#155e75",
    "swatch.2-bg": "#ecfeff",
    "swatch.2-border": "#a5f3fc",
    "swatch.3": "#3730a3",
    "swatch.3-bg": "#eef2ff",
    "swatch.3-border": "#c7d2fe",
    "swatch.4": "#86198f",
    "swatch.4-bg": "#fdf4ff",
    "swatch.4-border": "#f5d0fe",
    "swatch.5": "#3f6212",
    "swatch.5-bg": "#f7fee7",
    "swatch.5-border": "#d9f99d",
    "swatch.6": "#44403c",
    "swatch.6-bg": "#fafaf9",
    "swatch.6-border": "#e7e5e4",
    "text": "#0f172a",
    "text-2xl": "1.75rem",
    "text-2xs": "0.6875rem",
    "text-base": "0.875rem",
    "text-lg": "1.125rem",
    "text-md": "1rem",
    "text-muted": "#475569",
    "text-on-accent": "#ffffff",
    "text-sm": "0.8125rem",
    "text-subtle": "#64748b",
    "text-xl": "1.375rem",
    "text-xs": "0.75rem",
  },
  "dark": {
    "accent": "#67e8f9",
    "accent-border": "#1b4655",
    "accent-hover": "#a5f3fc",
    "accent-subtle": "#102a32",
    "bg": "#0a0d12",
    "bg-muted": "#181f28",
    "bg-subtle": "#11161d",
    "border": "#29333f",
    "border-strong": "#5d6c7e",
    "duration": "180ms",
    "duration-alert": "0ms",
    "duration-fast": "120ms",
    "duration-identity-escalate": "260ms",
    "duration-identity-reveal": "220ms",
    "duration-identity-swap": "180ms",
    "duration-skeleton-loop": "1400ms",
    "duration-slow": "280ms",
    "ease": "cubic-bezier(0.22, 1, 0.36, 1)",
    "flag.deceased": "#cbd5e1",
    "flag.provisional": "#fbbf24",
    "flag.restricted": "#c4b5fd",
    "flag.restricted-bg": "#1c1533",
    "focus-ring": "#67e8f9",
    "focus-ring-offset": "#0a0d12",
    "font-mono": "ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, monospace",
    "font-numeric": "ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, monospace",
    "font-sans": "ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif",
    "radius": "0.5rem",
    "radius-full": "9999px",
    "radius-lg": "0.75rem",
    "radius-sm": "0.25rem",
    "radius-xl": "1rem",
    "shadow": "0 1px 3px 0 rgb(0 0 0 / 0.5)",
    "shadow-lg": "0 16px 40px -10px rgb(0 0 0 / 0.65)",
    "shadow-md": "0 4px 14px -2px rgb(0 0 0 / 0.55)",
    "shadow-sm": "0 1px 2px 0 rgb(0 0 0 / 0.4)",
    "status.critical": "#fb7185",
    "status.critical-bg": "#2a1216",
    "status.critical-border": "#5c1f28",
    "status.high": "#fbbf24",
    "status.high-bg": "#2a1f0c",
    "status.high-border": "#5c421a",
    "status.low": "#60a5fa",
    "status.low-bg": "#0f1c33",
    "status.low-border": "#1e3a68",
    "status.normal": "#4ade80",
    "status.normal-bg": "#10271e",
    "status.normal-border": "#1e5138",
    "status.unknown": "#94a3b8",
    "status.unknown-bg": "#141f22",
    "status.unknown-border": "#253338",
    "surface": "#141a22",
    "surface-overlay": "#1d2630",
    "surface-raised": "#1a222c",
    "swatch.1": "#5eead4",
    "swatch.1-bg": "#10241f",
    "swatch.1-border": "#1d4c44",
    "swatch.2": "#67e8f9",
    "swatch.2-bg": "#0e2429",
    "swatch.2-border": "#1a4a55",
    "swatch.3": "#a5b4fc",
    "swatch.3-bg": "#171a33",
    "swatch.3-border": "#2e3468",
    "swatch.4": "#f0abfc",
    "swatch.4-bg": "#26102b",
    "swatch.4-border": "#50245a",
    "swatch.5": "#bef264",
    "swatch.5-bg": "#1a2110",
    "swatch.5-border": "#35441f",
    "swatch.6": "#d6d3d1",
    "swatch.6-bg": "#1c1b1a",
    "swatch.6-border": "#3a3735",
    "text": "#edf2f7",
    "text-2xl": "1.75rem",
    "text-2xs": "0.6875rem",
    "text-base": "0.875rem",
    "text-lg": "1.125rem",
    "text-md": "1rem",
    "text-muted": "#a5b1be",
    "text-on-accent": "#071014",
    "text-sm": "0.8125rem",
    "text-subtle": "#82909f",
    "text-xl": "1.375rem",
    "text-xs": "0.75rem",
  },
  "high-contrast": {
    "accent": "#005141",
    "accent-border": "#005141",
    "accent-hover": "#00332a",
    "accent-subtle": "#ffffff",
    "bg": "#ffffff",
    "bg-muted": "#f1f5f9",
    "bg-subtle": "#ffffff",
    "border": "#000000",
    "border-strong": "#000000",
    "duration": "180ms",
    "duration-alert": "0ms",
    "duration-fast": "120ms",
    "duration-identity-escalate": "260ms",
    "duration-identity-reveal": "220ms",
    "duration-identity-swap": "180ms",
    "duration-skeleton-loop": "1400ms",
    "duration-slow": "280ms",
    "ease": "cubic-bezier(0.22, 1, 0.36, 1)",
    "flag.deceased": "#000000",
    "flag.provisional": "#6b3000",
    "flag.restricted": "#4c1d95",
    "flag.restricted-bg": "#ffffff",
    "focus-ring": "#000000",
    "focus-ring-offset": "#ffffff",
    "font-mono": "ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, monospace",
    "font-numeric": "ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, monospace",
    "font-sans": "ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif",
    "radius": "0.5rem",
    "radius-full": "9999px",
    "radius-lg": "0.75rem",
    "radius-sm": "0.25rem",
    "radius-xl": "1rem",
    "shadow": "none",
    "shadow-lg": "none",
    "shadow-md": "none",
    "shadow-sm": "none",
    "status.critical": "#8a0000",
    "status.critical-bg": "#ffffff",
    "status.critical-border": "#8a0000",
    "status.high": "#6b3000",
    "status.high-bg": "#ffffff",
    "status.high-border": "#6b3000",
    "status.low": "#003a8c",
    "status.low-bg": "#ffffff",
    "status.low-border": "#003a8c",
    "status.normal": "#00513a",
    "status.normal-bg": "#ffffff",
    "status.normal-border": "#00513a",
    "status.unknown": "#333333",
    "status.unknown-bg": "#ffffff",
    "status.unknown-border": "#333333",
    "surface": "#ffffff",
    "surface-overlay": "#ffffff",
    "surface-raised": "#ffffff",
    "swatch.1": "#1f1f1f",
    "swatch.1-bg": "#ffffff",
    "swatch.1-border": "#000000",
    "swatch.2": "#1f1f1f",
    "swatch.2-bg": "#ffffff",
    "swatch.2-border": "#000000",
    "swatch.3": "#1f1f1f",
    "swatch.3-bg": "#ffffff",
    "swatch.3-border": "#000000",
    "swatch.4": "#1f1f1f",
    "swatch.4-bg": "#ffffff",
    "swatch.4-border": "#000000",
    "swatch.5": "#1f1f1f",
    "swatch.5-bg": "#ffffff",
    "swatch.5-border": "#000000",
    "swatch.6": "#1f1f1f",
    "swatch.6-bg": "#ffffff",
    "swatch.6-border": "#000000",
    "text": "#000000",
    "text-2xl": "1.75rem",
    "text-2xs": "0.6875rem",
    "text-base": "0.875rem",
    "text-lg": "1.125rem",
    "text-md": "1rem",
    "text-muted": "#1f1f1f",
    "text-on-accent": "#ffffff",
    "text-sm": "0.8125rem",
    "text-subtle": "#1f1f1f",
    "text-xl": "1.375rem",
    "text-xs": "0.75rem",
  },
};
