/**
 * A theme, in five formats.
 *
 * Two of these theme the customer's *own* components rather than ours, and
 * they are the reason this module is small: the antd and MUI exports are the
 * bridge mapping tables run backwards. A bridge reads `colorPrimary` and writes
 * `--ox-accent`; the export reads the customer's accent and writes
 * `colorPrimary`. Same correspondence, opposite direction — which is why they
 * stay correct automatically when a bridge is corrected.
 *
 * The commercial point is worth stating plainly: a customer who configures
 * their brand once and has their entire antd application pick it up is a
 * materially better story than one who has themed our components only.
 *
 * What no export carries is clinical status. Ours holds a validated contrast
 * floor and 60° of hue separation; an antd theme has nowhere to put either, so
 * writing `colorError` from `status.critical` would hand a customer a colour
 * stripped of everything that made it safe.
 */

import { toDtcg } from "@oxygenui-design/tokens/validate";
import type { ThemeDocument } from "./document";
import { emitThemeCss } from "./emit";

export type ExportFormat = "dtcg" | "css" | "tailwind" | "antd" | "mui";

export interface ExportResult {
  format: ExportFormat;
  filename: string;
  contentType: string;
  body: string;
  /** Stated at the point of use, never buried in documentation. */
  caveat?: string;
}

/** The DTCG document, in the spec's structured form. */
function toDtcgDocument(theme: ThemeDocument): string {
  // Built by mapping rather than by mutating a partially-initialised record:
  // the index-then-assign shape needs a non-null assertion to typecheck, and
  // the house rule forbids them because the one place an assertion is wrong is
  // the place nothing tells you.
  const ref = Object.fromEntries(
    Object.entries(theme.tokens.ref).map(([group, steps]) => [
      group,
      {
        $type: "color",
        ...Object.fromEntries(
          Object.entries(steps).map(([step, value]) => [step, { $value: toDtcg("color", value) }]),
        ),
      },
    ]),
  );

  return `${JSON.stringify(
    {
      $description:
        `${theme.name} — exported from the Oxygen theme console at version ${theme.version}. ` +
        "Primitive palette only: semantic tokens resolve to these, so overriding the palette " +
        "reaches every component without a theme being able to redefine what critical means.",
      ref,
    },
    null,
    2,
  )}\n`;
}

/** A Tailwind v4 `@theme` block. */
function toTailwind(theme: ThemeDocument): string {
  const lines: string[] = ["@theme {"];
  for (const [group, steps] of Object.entries(theme.tokens.ref)) {
    for (const [step, value] of Object.entries(steps)) {
      lines.push(`  --color-${group}-${step}: ${value};`);
    }
  }
  lines.push("}", "");
  return lines.join("\n");
}

/**
 * The antd export.
 *
 * `bridge-antd` maps `colorPrimary → --ox-accent`; this is that correspondence
 * read the other way. Only the tokens the bridge treats as honest counterparts
 * appear — writing every antd token from a palette we do not have equivalents
 * for would produce a theme that is uniformly slightly wrong.
 */
function toAntd(theme: ThemeDocument): string {
  const ramp = theme.tokens.ref.brand ?? {};
  const token: Record<string, string> = {};

  if (ramp["600"]) token.colorPrimary = ramp["600"];
  if (ramp["700"]) token.colorPrimaryHover = ramp["700"];
  if (ramp["50"]) token.colorPrimaryBg = ramp["50"];
  if (ramp["200"]) token.colorPrimaryBorder = ramp["200"];

  return `${[
    "// Generated by the Oxygen theme console.",
    "//",
    "// Your brand, in Ant Design's vocabulary — so your own antd components",
    "// pick it up, not only Oxygen's.",
    "//",
    "// Clinical status is deliberately absent. Oxygen's status colours carry a",
    "// validated contrast floor and 60 degrees of hue separation so the direction",
    "// of an abnormal result survives colour-vision deficiency; antd has nowhere",
    "// to record either, so exporting them would hand you a colour stripped of",
    "// everything that made it safe.",
    "",
    `export const ${identifier(theme.slug)}Theme = ${JSON.stringify({ token }, null, 2)};`,
  ].join("\n")}\n`;
}

/** The MUI export. `bridge-mui`'s table, backwards. */
function toMui(theme: ThemeDocument): string {
  const ramp = theme.tokens.ref.brand ?? {};
  const primary: Record<string, string> = {};

  if (ramp["600"]) primary.main = ramp["600"];
  if (ramp["700"]) primary.dark = ramp["700"];
  if (ramp["400"]) primary.light = ramp["400"];

  return `${[
    "// Generated by the Oxygen theme console.",
    "//",
    "// Your brand, in Material UI's vocabulary.",
    "//",
    "// Clinical status is deliberately absent — see the antd export for why.",
    "",
    'import { createTheme } from "@mui/material/styles";',
    "",
    `export const ${identifier(theme.slug)}Theme = createTheme(${JSON.stringify(
      { palette: { primary } },
      null,
      2,
    )});`,
  ].join("\n")}\n`;
}

/** `northwind-clinical` → `northwindClinical`, for a JS binding. */
function identifier(slug: string): string {
  return slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

export function exportTheme(theme: ThemeDocument, format: ExportFormat): ExportResult {
  const stem = `${theme.slug}@${theme.version}`;

  switch (format) {
    case "dtcg":
      return {
        format,
        filename: `${stem}.tokens.json`,
        contentType: "application/json",
        body: toDtcgDocument(theme),
        caveat:
          "Colour round-trips exactly. Dimension, duration and shadow are exported in the " +
          "spec's structured form and re-import unchanged.",
      };
    case "css":
      return {
        format,
        filename: `${stem}.css`,
        contentType: "text/css",
        body: emitThemeCss(theme),
      };
    case "tailwind":
      return {
        format,
        filename: `${stem}.tailwind.css`,
        contentType: "text/css",
        body: toTailwind(theme),
      };
    case "antd":
      return {
        format,
        filename: `${stem}.antd.ts`,
        contentType: "text/plain",
        body: toAntd(theme),
        caveat: "Chrome only. Clinical status keeps Oxygen's validated values.",
      };
    case "mui":
      return {
        format,
        filename: `${stem}.mui.ts`,
        contentType: "text/plain",
        body: toMui(theme),
        caveat: "Chrome only. Clinical status keeps Oxygen's validated values.",
      };
  }
}

/* -------------------------------------------------------------------------- */
/* Import                                                                     */
/* -------------------------------------------------------------------------- */

export interface ImportReport {
  /** Palette steps understood. */
  matched: Record<string, Record<string, string>>;
  /** Keys present in the file that mean nothing here, with their paths. */
  unmatched: string[];
  /**
   * Clinical tokens found and discarded.
   *
   * Reported rather than silently dropped: a customer whose file contained a
   * status colour needs to know it did not take effect, and needs to know
   * *before* they confirm — otherwise the first they hear of it is a support
   * conversation about a red that did not change.
   */
  discardedClinical: string[];
}

const CLINICAL_PATH = /^(status|flag)\./;

/**
 * Read a DTCG document into a palette.
 *
 * Deliberately conservative. Only `ref.*` colour steps are taken, because that
 * is the whole surface a theme is allowed to set; everything else is reported
 * as unmatched rather than guessed at. An import that quietly ignores half a
 * file is how a customer concludes the import worked.
 */
export function importDtcg(document: unknown): ImportReport {
  const matched: Record<string, Record<string, string>> = {};
  const unmatched: string[] = [];
  const discardedClinical: string[] = [];

  const walk = (node: unknown, path: string[]): void => {
    if (!node || typeof node !== "object") return;
    const record = node as Record<string, unknown>;

    if ("$value" in record) {
      const dotted = path.join(".");

      if (CLINICAL_PATH.test(dotted)) {
        discardedClinical.push(dotted);
        return;
      }

      const [head, group, step] = path;
      if (head === "ref" && group && step && typeof record.$value === "string") {
        (matched[group] ??= {})[step] = record.$value;
        return;
      }
      unmatched.push(dotted);
      return;
    }

    for (const [key, child] of Object.entries(record)) {
      if (key.startsWith("$")) continue;
      walk(child, [...path, key]);
    }
  };

  walk(document, []);
  return { matched, unmatched, discardedClinical };
}

/**
 * Read an antd or MUI theme object into a palette.
 *
 * Lossy in one direction and the UI must say so: neither framework has a
 * concept of clinical status, so those tokens keep Oxygen's validated values
 * rather than arriving from the file.
 */
export function importFrameworkTheme(theme: unknown): ImportReport {
  const matched: Record<string, Record<string, string>> = {};
  const unmatched: string[] = [];
  const record = (theme ?? {}) as Record<string, unknown>;

  const antd = record.token as Record<string, unknown> | undefined;
  const mui = (record.palette as Record<string, unknown> | undefined)?.primary as
    Record<string, unknown> | undefined;

  const brand: Record<string, string> = {};
  const take = (value: unknown, step: string) => {
    if (typeof value === "string") brand[step] = value;
  };

  take(antd?.colorPrimary ?? mui?.main, "600");
  take(antd?.colorPrimaryHover ?? mui?.dark, "700");
  take(antd?.colorPrimaryBg, "50");
  take(mui?.light, "400");

  if (Object.keys(brand).length) matched.brand = brand;

  for (const key of Object.keys(antd ?? {})) {
    if (
      !["colorPrimary", "colorPrimaryHover", "colorPrimaryBg", "colorPrimaryBorder"].includes(key)
    ) {
      unmatched.push(`token.${key}`);
    }
  }

  return {
    matched,
    unmatched,
    // Always. Neither framework can express the direction of an abnormal
    // result, so there is nothing here that could have carried it.
    discardedClinical: ["status.*", "flag.*"],
  };
}
