/**
 * Rasterise the site mark into the icon files browsers actually ask for.
 *
 * `apps/docs/src/app/icon.svg` is the master and the only place the artwork
 * lives. Everything else is derived from it and committed:
 *
 *   icon.svg        the master, copied into the two apps that had none
 *   favicon.ico     16 / 32 / 48
 *   apple-icon.png  180, for the iOS home screen
 *
 * The `.ico` is not redundant with the SVG. Every consumer that never parses
 * the document — search results, feed readers, link unfurls, an OS bookmark —
 * requests `/favicon.ico` blind, and all three hosts answered 404.
 *
 * Chromium rasterises, because it is the renderer that has to agree with the
 * result, and each size is rendered natively rather than downscaled from one
 * large frame: the master's strokes are weighted for 16px, and downscaling
 * throws that weighting away.
 *
 *   pnpm icons
 */
import { chromium } from "@playwright/test";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const MASTER = path.join(ROOT, "apps/docs/src/app/icon.svg");
const APP_DIRS = ["apps/docs/src/app", "apps/app/src/app", "apps/hq/src/app"];

/** What a browser asks an .ico for. 16 is the one that decides. */
const ICO_SIZES = [16, 32, 48];
const APPLE_SIZE = 180;

/** Next resolves `icon.svg` per app directory, so the other two get a copy. */
const COPY_BANNER =
  "<!-- Generated by `pnpm icons`. Edit apps/docs/src/app/icon.svg instead. -->\n";

/**
 * Pack PNGs into an ICO: header, one 16-byte directory entry each, then the
 * frames. PNG-in-ICO rather than BMP — every browser and Windows since Vista
 * reads it, and it keeps the alpha without a second encoder.
 */
function ico(frames: readonly { size: number; png: Buffer }[]): Buffer {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(1, 2); // 1 = icon, not cursor
  header.writeUInt16LE(frames.length, 4);

  const directory = Buffer.alloc(16 * frames.length);
  let offset = header.length + directory.length;

  frames.forEach((frame, index) => {
    const at = 16 * index;
    // 256 is written as 0. Nothing here is that large, but the rule is the format's.
    directory.writeUInt8(frame.size % 256, at);
    directory.writeUInt8(frame.size % 256, at + 1);
    directory.writeUInt16LE(1, at + 4); // colour planes
    directory.writeUInt16LE(32, at + 6); // bits per pixel
    directory.writeUInt32LE(frame.png.length, at + 8);
    directory.writeUInt32LE(offset, at + 12);
    offset += frame.png.length;
  });

  return Buffer.concat([header, directory, ...frames.map((frame) => frame.png)]);
}

/**
 * The Apple tile is the same artwork on a square, inset ground.
 *
 * Square because iOS applies its own corner mask, and a mark that arrives
 * already rounded gets rounded twice and reads as inset from its own tile.
 * Inset because the master fills its box edge to edge, which is right in a
 * 16px browser tab and looks like it is bursting out of a home-screen icon.
 * The ground is the master's own — read off the rect, not restated here.
 */
function appleTile(master: string): string {
  const rect = /<rect\b[^>]*\bfill="([^"]+)"[^>]*\/>/.exec(master);
  if (!rect) throw new Error(`No ground rect found in ${MASTER}`);

  return `<div style="width:100%;height:100%;display:grid;place-items:center;background:${rect[1]}">
    ${master.replace(rect[0], "")}
  </div>`;
}

async function main() {
  const master = await readFile(MASTER, "utf8");
  const browser = await chromium.launch();
  const page = await browser.newPage();

  /** One frame, rendered at its final size rather than scaled down to it. */
  async function render(markup: string, size: number, scale = 1): Promise<Buffer> {
    await page.setViewportSize({ width: size, height: size });
    await page.setContent(
      `<style>html,body{margin:0;height:100%}svg{display:block;width:${Math.round(size * scale)}px;height:${Math.round(size * scale)}px}</style>${markup}`,
    );
    return page.screenshot({ omitBackground: true });
  }

  // Sequential, not `Promise.all`: one page, and the viewport is what sets the
  // size — rendered concurrently the last `setViewportSize` wins and every
  // frame comes out at 48.
  const frames: { size: number; png: Buffer }[] = [];
  for (const size of ICO_SIZES) {
    frames.push({ size, png: await render(master, size) });
  }

  const favicon = ico(frames);
  const apple = await render(appleTile(master), APPLE_SIZE, 0.78);

  await browser.close();

  for (const dir of APP_DIRS) {
    const absolute = path.join(ROOT, dir);
    if (absolute !== path.dirname(MASTER)) {
      await writeFile(path.join(absolute, "icon.svg"), COPY_BANNER + master);
    }
    await writeFile(path.join(absolute, "favicon.ico"), favicon);
    await writeFile(path.join(absolute, "apple-icon.png"), apple);
    console.log(`wrote ${dir}/{icon.svg,favicon.ico,apple-icon.png}`);
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
